using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace RentalTracker.DAL.Exceptions
{
    /// <summary>
    /// Represents the exception that occurs during validation of a data field when the ValidationAttribute class is used. 
    /// </summary>
    [Serializable]
    public class RentalTrackerServiceValidationException : Exception
    {
        /// <summary>
        /// A collection of ValidationResult results that describe all the errors.
        /// </summary>
        private IEnumerable<ValidationResult> validationResults;

        /// <summary>
        /// Initializes a new instance of the RentalTrackerServiceValidationException class
        /// using an error message generated by the system.
        /// </summary>
        public RentalTrackerServiceValidationException()
        {
        }

        /// <summary>
        /// Initializes a new instance of the RentalTrackerServiceValidationException class
        /// using a specified error message.
        /// </summary>
        /// <param name="message">The sepcified message.</param>
        public RentalTrackerServiceValidationException(string message) : base(message)
        {
        }

        /// <summary>
        /// Initializes a new instance of the RentalTrackerServiceValidationException class by 
        /// using a specified error message, and a collection of ValidationResults.
        /// </summary>
        /// <param name="message">The sepcified message.</param>
        /// <param name="validationResults">A collection of ValidationResult results.</param>
        public RentalTrackerServiceValidationException(string message, IEnumerable<ValidationResult> validationResults) : base(message)
        {
            this.validationResults = validationResults;
        }

        /// <summary>
        /// Gets the ValidationResult instance that describes the validation error.
        /// </summary>
        public IEnumerable<ValidationResult> ValidationResults
        {
            get { return validationResults ?? new List<ValidationResult>(); }
        }
    }
}