// <auto-generated />
namespace RentalTracker.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_Payee_and_Category_keys : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_Payee_and_Category_keys));
        
        string IMigrationMetadata.Id
        {
            get { return "201701121313386_add_Payee_and_Category_keys"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
