// <auto-generated />
namespace RentalTracker.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_Taxable_column_to_Transaction : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_Taxable_column_to_Transaction));
        
        string IMigrationMetadata.Id
        {
            get { return "201702021437594_add_Taxable_column_to_Transaction"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
