// <auto-generated />
namespace RentalTracker.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class make_category_required_in_Payee_and_Transaction : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(make_category_required_in_Payee_and_Transaction));
        
        string IMigrationMetadata.Id
        {
            get { return "201701181118338_make_category_required_in_Payee_and_Transaction"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
