// <auto-generated />
namespace RentalTracker.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class remove_Number_column_and_reduce_size_of_Reference_column : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_Number_column_and_reduce_size_of_Reference_column));
        
        string IMigrationMetadata.Id
        {
            get { return "201701181503322_remove_Number_column_and_reduce_size_of_Reference_column"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
